### ISSUE TITLE
Failed to load plugin obsidian-journey-plugin

### ISSUE THREAD

**Issue by Teitei011** [akaalias/obsidian-journey-plugin#1]
Hi,

I´m trying to install the plugin in my obsidian vault but this error keeps showing up ("Failed to load plugin obsidian-journey-plugin"). I have put the obsidian-journey-plugin file inside ".obsidian\plugins\" but it´s not working, don´t know what is the problem

Btw, Love your plugin

Peace, 

Stefan

**Comment by akaalias** [comment]
Hey @Teitei011 – Sorry for the confusion! It's not yet working because I had not pushed a release yet. The github repo you downloaded only has the source-files but is missing the actual "compiled" version of the plugin. 

I just created the first official release -> https://github.com/akaalias/obsidian-journey-plugin/releases/tag/0.0.3

To give it a spin, do this for now (until we're in the plugin directory) 

1. Download the release files 
2. Create a folder called "obsidian-journey-plugin" in ".obsidian\plugins"
3. Drop the 3 files (main.js, mainfest.json and styles.css) in this folder
4. Refresh your Obsidian
5. Enable the plugin in your list of plugins

Let me know if you have any questions and thank you for your interest1! :)
