### ISSUE TITLE
Thank you for your development. It has been simplified and modified. Please review it

### ISSUE THREAD

**Issue by obsidian-canzi** [akaalias/obsidian-journey-plugin#3]
ResultsModal.prototype.createClipboardContent = function () {
        var result = "### 笔记旅程\n [[" + this.results.first() + "]] → [[" + this.results.last() + "]] 途经：\n";
        // @ts-ignore
        this.results.forEach(function (x) {
            result += "1. [[" + x + "]]\n";
        });
        return result;
    };

**Comment by akaalias** [comment]
Hi @canzi-teacher – Thank you for your submission! I understand that you would like the option to automatically turn the note titles into markdown links. I personally prefer not to do that because it will create an MOC (map of content) where I don't want one. 

How about this: I'll add it to the list of future features and let the community decide if this should be an option. I think some will want it. But not everyone. 

Thanks!
